version: "3.9"
services:
  blog-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - ./blog-db:/var/lib/mysql
  blog-api:
    build: blog-api
    ports:
      - "3000:3000"
    volumes:
      - ./blog-api:/usr/src/app
  blog-web:
    build: blog-web
    ports:
      - "3001:3000"
    volumes:
      - ./blog-web:/usr/src/app

