version: "3.9"
services:
  blog-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./blog-db:/var/lib/mysql
    networks:
      - backend
  blog-api:
    build: blog-api
    volumes:
      - ./blog-api:/usr/src/app
    networks:
      - backend
      - frontend
  blog-web:
#    build: blog-web
    image: aws-1-docker_blog-web
    ports:
      - "3001:3000"
    volumes:
      - ./blog-web:/usr/src/app
    networks:
      - frontend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

